.deploy:
  image: python:3.9
  cache:
    paths: []
  before_script:
    - pip install awscli
    - apt-get update -y
    - apt-get install -y zip htpdate
    - htpdate -a google.com
    - mkdir ~/.aws/
    - touch ~/.aws/credentials

deploy:staging:
  extends: .deploy
  stage: deploy
  environment:
    name: staging
  dependencies:
    - build:staging
  when: manual
  only:
    refs:
      - staging
      - contact-us
  script:
    - printf "[default]\naws_access_key_id = %s\naws_secret_access_key = %s\nregion = %s\n" "$AWS_TEST_ACCESS_KEY_ID" "$AWS_TEST_SECRET_ACCESS_KEY" "$AWS_TEST_REGION" >> ~/.aws/credentials
    - export VERSION_LABEL="${CI_COMMIT_SHA}-${AWS_TEST_EB_APP_ENVIRONMENT_NAME_STAGING}-$(date +%s)"
    # Deploy web
    - bash aws/web/build.sh
    - cd build_web && zip -qq -r "${CI_COMMIT_SHA}.zip" . ??* && cd ..
    - aws s3 cp "build_web/${CI_COMMIT_SHA}.zip" "s3://${AWS_TEST_EB_BUCKET_NAME}/${AWS_TEST_EB_APP_NAME}/${AWS_TEST_EB_APP_ENVIRONMENT_NAME_STAGING}/${CI_COMMIT_SHA}.zip"
    - aws elasticbeanstalk create-application-version --application-name "${AWS_TEST_EB_APP_NAME}" --version-label "$VERSION_LABEL" --source-bundle S3Bucket="${AWS_TEST_EB_BUCKET_NAME}",S3Key="${AWS_TEST_EB_APP_NAME}/${AWS_TEST_EB_APP_ENVIRONMENT_NAME_STAGING}/${CI_COMMIT_SHA}.zip" --region "${AWS_TEST_REGION}"
    - aws elasticbeanstalk update-environment --environment-name "${AWS_TEST_EB_APP_ENVIRONMENT_NAME_STAGING}" --application-name "${AWS_TEST_EB_APP_NAME}" --version-label "$VERSION_LABEL" --region "${AWS_TEST_REGION}"
#    # Deploy worker
#    - bash aws/worker/build.sh
#    - cd build_worker && zip -qq -r "${CI_COMMIT_SHA}.zip" . ??* && cd ..
#    - aws s3 cp "build_worker/${CI_COMMIT_SHA}.zip" "s3://${AWS_TEST_EB_BUCKET_NAME}/${AWS_TEST_EB_QUEUE_NAME}/${AWS_TEST_EB_QUEUE_ENVIRONMENT_NAME_STAGING}/${CI_COMMIT_SHA}.zip"
#    - aws elasticbeanstalk create-application-version --application-name "${AWS_TEST_EB_QUEUE_NAME}" --version-label "$VERSION_LABEL" --source-bundle S3Bucket="${AWS_TEST_EB_BUCKET_NAME}",S3Key="${AWS_TEST_EB_QUEUE_NAME}/${AWS_TEST_EB_QUEUE_ENVIRONMENT_NAME_STAGING}/${CI_COMMIT_SHA}.zip" --region "${AWS_TEST_REGION}"
#    - aws elasticbeanstalk update-environment --environment-name "${AWS_TEST_EB_QUEUE_ENVIRONMENT_NAME_STAGING}" --application-name "${AWS_TEST_EB_QUEUE_NAME}" --version-label "$VERSION_LABEL" --region "${AWS_TEST_REGION}"

deploy:prod:
  extends: .deploy
  stage: deploy
  environment:
    name: prod
  dependencies:
    - build:prod
  when: manual
  only:
    refs:
      - prod
  script:
    - printf "[default]\naws_access_key_id = %s\naws_secret_access_key = %s\nregion = %s\n" "$AWS_PROD_ACCESS_KEY_ID" "$AWS_PROD_SECRET_ACCESS_KEY" "$AWS_PROD_REGION" >> ~/.aws/credentials
    - export VERSION_LABEL="${CI_COMMIT_SHA}-${AWS_PROD_EB_APP_ENVIRONMENT_NAME}-$(date +%s)"
    # Deploy web
    - bash aws/web/build.sh
    - cd build_web && zip -qq -r "${CI_COMMIT_SHA}.zip" . ??* && cd ..
    - aws s3 cp "build_web/${CI_COMMIT_SHA}.zip" "s3://${AWS_PROD_EB_BUCKET_NAME}/${AWS_PROD_EB_APP_NAME}/${AWS_PROD_EB_APP_ENVIRONMENT_NAME}/${CI_COMMIT_SHA}.zip"
    - aws elasticbeanstalk create-application-version --application-name "${AWS_PROD_EB_APP_NAME}" --version-label "$VERSION_LABEL" --source-bundle S3Bucket="${AWS_PROD_EB_BUCKET_NAME}",S3Key="${AWS_PROD_EB_APP_NAME}/${AWS_PROD_EB_APP_ENVIRONMENT_NAME}/${CI_COMMIT_SHA}.zip" --region "${AWS_PROD_REGION}"
    - aws elasticbeanstalk update-environment --environment-name "${AWS_PROD_EB_APP_ENVIRONMENT_NAME}" --application-name "${AWS_PROD_EB_APP_NAME}" --version-label "$VERSION_LABEL" --region "${AWS_PROD_REGION}"
#    # Deploy worker
#    - bash aws/worker/build.sh
#    - cd build_worker && zip -qq -r "${CI_COMMIT_SHA}.zip" . ??* && cd ..
#    - aws s3 cp "build_worker/${CI_COMMIT_SHA}.zip" "s3://${AWS_PROD_EB_BUCKET_NAME}/${AWS_PROD_EB_QUEUE_NAME}/${AWS_PROD_EB_QUEUE_ENVIRONMENT_NAME}/${CI_COMMIT_SHA}.zip"
#    - aws elasticbeanstalk create-application-version --application-name "${AWS_PROD_EB_QUEUE_NAME}" --version-label "$VERSION_LABEL" --source-bundle S3Bucket="${AWS_PROD_EB_BUCKET_NAME}",S3Key="${AWS_PROD_EB_QUEUE_NAME}/${AWS_PROD_EB_QUEUE_ENVIRONMENT_NAME}/${CI_COMMIT_SHA}.zip" --region "${AWS_PROD_REGION}"
#    - aws elasticbeanstalk update-environment --environment-name "${AWS_PROD_EB_QUEUE_ENVIRONMENT_NAME}" --application-name "${AWS_PROD_EB_QUEUE_NAME}" --version-label "$VERSION_LABEL" --region "${AWS_PROD_REGION}"


deploy:qa:
  extends: .deploy
  stage: deploy
  environment:
    name: qa
  dependencies:
    - build:qa
  only:
    refs:
      - qa
  script:
    - printf "[default]\naws_access_key_id = %s\naws_secret_access_key = %s\nregion = %s\n" "$AWS_TEST_ACCESS_KEY_ID" "$AWS_TEST_SECRET_ACCESS_KEY" "$AWS_TEST_REGION" >> ~/.aws/credentials
    - export VERSION_LABEL="${CI_COMMIT_SHA}-${AWS_TEST_EB_APP_ENVIRONMENT_NAME_QA}-$(date +%s)"
    # Deploy web
    - ls -la
    - bash aws/web/build.sh
    - cd build_web && zip -qq -r "${CI_COMMIT_SHA}.zip" . ??* && cd ..
    - aws s3 cp "build_web/${CI_COMMIT_SHA}.zip" "s3://${AWS_TEST_EB_BUCKET_NAME}/${AWS_TEST_EB_APP_NAME}/${AWS_TEST_EB_APP_ENVIRONMENT_NAME_QA}/${CI_COMMIT_SHA}.zip"
    - aws elasticbeanstalk create-application-version --application-name "${AWS_TEST_EB_APP_NAME}" --version-label "$VERSION_LABEL" --source-bundle S3Bucket="${AWS_TEST_EB_BUCKET_NAME}",S3Key="${AWS_TEST_EB_APP_NAME}/${AWS_TEST_EB_APP_ENVIRONMENT_NAME_QA}/${CI_COMMIT_SHA}.zip" --region "${AWS_TEST_REGION}"
    - aws elasticbeanstalk update-environment --environment-name "${AWS_TEST_EB_APP_ENVIRONMENT_NAME_QA}" --application-name "${AWS_TEST_EB_APP_NAME}" --version-label "$VERSION_LABEL" --region "${AWS_TEST_REGION}"
#    # Deploy worker
#    - bash aws/worker/build.sh
#    - cd build_worker && zip -qq -r "${CI_COMMIT_SHA}.zip" . ??* && cd ..
#    - aws s3 cp "build_worker/${CI_COMMIT_SHA}.zip" "s3://${AWS_TEST_EB_BUCKET_NAME}/${AWS_TEST_EB_QUEUE_NAME}/${AWS_TEST_EB_QUEUE_ENVIRONMENT_NAME_QA}/${CI_COMMIT_SHA}.zip"
#    - aws elasticbeanstalk create-application-version --application-name "${AWS_TEST_EB_QUEUE_NAME}" --version-label "$VERSION_LABEL" --source-bundle S3Bucket="${AWS_TEST_EB_BUCKET_NAME}",S3Key="${AWS_TEST_EB_QUEUE_NAME}/${AWS_TEST_EB_QUEUE_ENVIRONMENT_NAME_QA}/${CI_COMMIT_SHA}.zip" --region "${AWS_TEST_REGION}"
#    - aws elasticbeanstalk update-environment --environment-name "${AWS_TEST_EB_QUEUE_ENVIRONMENT_NAME_QA}" --application-name "${AWS_TEST_EB_QUEUE_NAME}" --version-label "$VERSION_LABEL" --region "${AWS_TEST_REGION}"
